name: Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout buildx repository
        uses: actions/checkout@v2
        with:
          repository: docker/buildx

      - name: Get SHA for buildx repo
        id: sha
        run: echo "::set-output name=shortsha::$(cd $GITHUB_WORKSPACE && git log --pretty=format:'%h' -n 1)"

      - name: Build buildx
        run: make install

      - name: List Files
        run: ls -alR .
      
      - name: rename build
        run: sudo mv hadoop-dist/target/hadoop-3.4.0-SNAPSHOT.tar.gz hadoop-dist/target/hadoop-3.4.0-SNAPSHOT-${{ steps.sha.outputs.shortsha }}.tar.gz

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "final"
          prerelease: false
          title: "Build"
          files: hadoop-dist/target/hadoop*gz